### ISSUE TITLE
4eSport

### ISSUE THREAD

**Issue by Mateleo** [Okampus/okampus#55]
### Pour quelle partie de l'infrastructure souhaitez-vous proposer une suggestion ?

Site Web

### Votre idée

A modifier
Description : 
4eSport est l’association de jeux vidéo de l'Efrei. Elle regroupe en son sein une multitude de pôles regroupant l’ensemble des jeux esportifs du moment. Elle est ouverte à tous sans condition.

Lien du site : https://4esport.fr/

Faut changer la photo aussi c'est pas nous

### Autre contexte

//

**Comment by iv-stpn** [comment]
Hello @Mateleo 

Les issues sur GitHub ne concernent que la codebase de la plateforme et son contenu statique. Il n'y a aucun contenu statique lié à 4eSport dans la codebase d'Okampus.

La Discord est plus adapté pour toute problématique liée à du contenu dynamique sur l'une des instances d'Okampus.

Je ferme donc l'issue.

J'ai sinon bien modifié la description, n'hésite pas à m'envoyer d'autres photos pour remplacer celles actuellement présentes !
